"""Fetch Soundslice notation data for GuitarToday tabs.

Reads slice IDs from the catalog CSV (generated by parse_patreon_posts.py),
then uses Playwright to load each slice page, intercept the data1.json and
sync JSON network requests, and save them locally.

Usage:
    python scripts/data/guitartoday/fetch_soundslice.py --headless
    python scripts/data/guitartoday/fetch_soundslice.py --headless --limit 5
"""

import csv
import json
import random
import time
import argparse
from pathlib import Path
from playwright.sync_api import sync_playwright

from gtp import REPO_ROOT
CATALOG_CSV = REPO_ROOT / 'data' / 'guitartoday' / 'posts.csv'
OUTPUT_DIR = REPO_ROOT / 'data' / 'guitartoday' / 'slices'
COOKIES_PATH = REPO_ROOT / 'data' / 'guitartoday' / 'soundslice_cookies.json'


def load_slice_ids():
    """Read Soundslice IDs from the catalog CSV. Skips entries without a slice ID."""
    ids = []
    with open(CATALOG_CSV) as f:
        for row in csv.DictReader(f):
            ss_id = row.get('soundslice_id', '').strip()
            if ss_id:
                ids.append(ss_id)
    return ids


def fetch_slice(page, slice_id, output_dir):
    """Navigate to a slice page, capture data1.json and sync JSON."""
    slice_dir = output_dir / slice_id
    data_path = slice_dir / 'data.json'
    sync_path = slice_dir / 'sync.json'

    if data_path.exists():
        return 'skip'

    captured = {}

    def handle_response(response):
        url = response.url
        if 'files.soundslice.com/data/json/' in url:
            try:
                body = response.json()
                if 'data1.json' in url:
                    captured['data'] = body
                elif 'syncpoint' in url:
                    captured['sync'] = body
                else:
                    if 'data' not in captured and isinstance(body, dict) and 'bars' in body:
                        captured['data'] = body
                    elif 'sync' not in captured and isinstance(body, list):
                        captured['sync'] = body
            except Exception:
                pass

    page.on('response', handle_response)

    try:
        page.goto(f'https://www.soundslice.com/slices/{slice_id}/', timeout=30000)
        page.wait_for_timeout(5000)
    except Exception as e:
        page.remove_listener('response', handle_response)
        return f'error: {e}'

    page.remove_listener('response', handle_response)

    if 'data' not in captured:
        return 'no data captured'

    slice_dir.mkdir(parents=True, exist_ok=True)
    with open(data_path, 'w') as f:
        json.dump(captured['data'], f, indent=2)

    if 'sync' in captured:
        with open(sync_path, 'w') as f:
            json.dump(captured['sync'], f, indent=2)

    n_bars = len(captured['data'].get('bars', []))
    has_sync = 'sync' in captured
    return f'ok ({n_bars} bars, sync={"yes" if has_sync else "no"})'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--headless', action='store_true', help='Run headless (after initial login)')
    parser.add_argument('--limit', type=int, default=None, help='Process only first N slices')
    args = parser.parse_args()

    slice_ids = load_slice_ids()
    print(f'Catalog: {len(slice_ids)} slices with Soundslice IDs')

    if args.limit:
        slice_ids = slice_ids[:args.limit]
        print(f'Limited to {args.limit}')

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=args.headless)
        context = browser.new_context()

        # Load saved cookies if available (not needed for public slices, but just in case)
        if COOKIES_PATH.exists():
            cookies = json.loads(COOKIES_PATH.read_text())
            context.add_cookies(cookies)
            print('Loaded saved cookies')

        page = context.new_page()

        done = 0
        skipped = 0
        failed = 0

        for i, slice_id in enumerate(slice_ids):
            result = fetch_slice(page, slice_id, OUTPUT_DIR)

            if result == 'skip':
                skipped += 1
                status = 'SKIP'
            elif result.startswith('ok'):
                done += 1
                status = result
            else:
                failed += 1
                status = f'FAIL: {result}'

            print(f'[{i+1:3d}/{len(slice_ids)}] {slice_id}: {status}')

            if result != 'skip':
                delay = random.uniform(2, 5)
                time.sleep(delay)

        page.close()
        browser.close()

    print(f'\n=== Summary ===')
    print(f'Downloaded: {done}')
    print(f'Skipped (already exists): {skipped}')
    print(f'Failed: {failed}')
    print(f'Output: {OUTPUT_DIR}')


if __name__ == '__main__':
    main()
